version: "3"

dotenv: [".env"]

tasks:
  default:
    desc: "The default task"
    cmds:
      - clear
      - task: test
  test: 
    cmds:
      - go test -run TestXxx github.com/117503445/otsutils -v -count=1